version: "3.9"

services:
  models_roberta_tfidf:
    env_file:
      - .env
    container_name: models_roberta_tfidf 
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "8987:8989"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]     